language: node_js
node_js:
  - "8"
# node 10 will not work until dependency on leveldown is upgraded from ^1.6.0
# Same issue as here, I think (bengo.is) https://github.com/atom/electron-link/pull/12
#  - "10"
